### ====== YOUTUBE CONSTANTS ====== ###
YT_SOURCE_PATH = "yt_source"
YT_SOURCE_MAX_SIZE = 1000 # IN MB
YT_SOURCE_WARNING_THRESHOLD = 2000 # IN MB
YT_SOURCE_CRITICAL_THRESHOLD = 4000 # IN MB
YT_SOURCE_CHECK_INTERVAL = 10 # Minutes